---
- hosts: repository
  user: root
  tasks:
  - name: Create repository root directory
    file: path="{{ splunk_repository.repository_root }}"
          state=directory
  
  - name: Create repository apps directory
    file: path="{{ splunk_repository.repository_root }}/apps"
          state=directory

  - name: Create repository packages directory
    file: path="{{ splunk_repository.repository_root }}/packages"
          state=directory

  - name: Create distServerKeys directory
    file: path="{{ splunk_repository.repository_root }}/distServerKeys"
          state=directory

  - name: Set repository owner/group
    file: path={{ splunk_repository.repository_root }} 
          recurse=yes 
          owner={{ splunk_repository.repository_owner }} 
          group={{ splunk_repository.repository_group }}

  - name: Set repository directory mode
    file: path={{ splunk_repository.repository_root }} 
          mode=750

