---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

# site_replication_factor

- name: "Configure server.conf [clustering] - site_replication_factor state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=site_replication_factor
            value="{{ splunk_server_conf.clustering.site_replication_factor }}"
            state=present
  when: splunk_server_conf.clustering.site_replication_factor is defined or
        splunk_server_conf.clustering.site_replication_factor != "origin:2, total:3"
  notify: splunk restart

- name: "Configure server.conf [clustering] - site_replication_factor state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=site_replication_factor
            state=absent
  when: splunk_server_conf.clustering.site_replication_factor is undefined or
        splunk_server_conf.clustering.site_replication_factor == "origin:2, total:3"
  notify: splunk restart

