---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [replication_port-ssl:<port>]
#####################################################################################################################

- name: "Configure server.conf [replication_port-ssl:<port>] - replication_port-ssl state=present"
  ini_file: dest="{{ splunk_conf_path }}/server.conf"
            section="replication_port-ssl://{{ splunk_server_conf.replication_port_ssl.port }}"
            state=present
  when: splunk_server_conf.replication_port_ssl.port is defined
  notify: splunk restart

- name: "Configure server.conf [replication_port-ssl:<port>] - replication_port-ssl check presence"
  shell: grep 'replication_port-ssl:' {{ splunk_conf_path }}/server.conf | sed 's/\[replication_port-ssl:\/\/\(.*\)]/\1/'
  register: splunk_server_replication_port_ssl_port_inifile
  changed_when: false
  notify: splunk restart

- name: "Configure server.conf [replication_port-ssl:<port>] - replication_port-ssl state=absent (default)"
  ini_file: dest="{{ splunk_conf_path }}/server.conf"
            section="replication_port-ssl://{{ splunk_server_replication_port_ssl_port_inifile.stdout }}"
            state=absent
  when: splunk_server_conf.replication_port_ssl.port is undefined and
        splunk_server_replication_port_ssl_port_inifile.stdout != ""
  notify: splunk restart
