---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [replication_port-ssl:<port>]
#####################################################################################################################

# serverCert

- name: "Configure server.conf [replication_port-ssl:<port>] - serverCert state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section="replication_port-ssl://{{ splunk_server_conf.replication_port_ssl.port }}"
            option=serverCert
            value={{ splunk_server_conf.replication_port_ssl.serverCert }}
            state=present
  when: splunk_server_conf.replication_port_ssl.serverCert is defined

- name: "Configure server.conf [replication_port-ssl:<port>] - serverCert state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section="replication_port-ssl://{{ splunk_server_conf.replication_port_ssl.port }}"
            option=serverCert
            state=absent
  when: splunk_server_conf.replication_port_ssl is defined and
        splunk_server_conf.replication_port_ssl.serverCert is undefined

