---

- name: Create Splunk unix group
  group: name=splunk
         state=present
  when: splunk_installation.package_format != "rpm"

- name: Create Splunk unix user
  user: name=splunk 
        group=splunk
        state=present
        comment="Splunk Server"
        shell="/bin/bash"
        home="/opt/splunk"
        password="!!"
  when: splunk_installation.package_format != "rpm"

- name: Copy Splunk package
  copy: src="{{ splunk_repository.repository_root }}/packages/{{ splunk_installation.package_file }}"
        dest="/{{ splunk_installation.remote_package_path }}/{{ splunk_installation.package_file }}"
        mode=600

- name: Install Splunk package from rpm
  yum: name="{{ splunk_installation.remote_package_path }}/{{ splunk_installation.package_file }}" 
       state=present
  when: splunk_installation.package_format == "rpm"

- name: Install Splunk package from tgz
  unarchive: src="{{ splunk_installation.remote_package_path }}/{{ splunk_installation.package_file }}"
             dest=/opt
             copy=no
  when:  splunk_installation.package_format == "tgz"

- name: Remove Splunk package
  command: rm "{{ splunk_installation.remote_package_path }}/{{ splunk_installation.package_file }}"
  when: splunk_installation.delete_package_after_install != false

- name: Set permissions for $SPLUNK_HOME 
  file: path="{{ splunk_installation.splunk_home_path }}" 
        owner=splunk
        group=splunk
        recurse=yes
  when: splunk_installation.package_format == "tgz"
