---
- include: install_splunk.yml
- include: set_splunk_secret.yml
- include: enable_boot_start_splunk.yml
- include: change_default_password.yml
- include: add_authorized_key.yml
- include: firewalld_open_splunkports.yml
