---
#####################################################################################################################
# Configurations for Splunk inputs.conf
#####################################################################################################################

#####################################################################################################################
# [splunktcp-ssl:<port>]
#####################################################################################################################

- name: "Configure inputs.conf [splunktcp-ssl:<port>] - splunktcp-ssl state=present"
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=splunktcp-ssl:{{ splunk_inputs_conf.splunktcp_ssl.port }}  
            state=present
  when: splunk_inputs_conf.splunktcp_ssl.port is defined

- name: "Configure inputs.conf [splunktcp-ssl:<port>] - splunktcp-ssl state=absent (default)"
  replace: dest="{{ splunk_conf_path }}/inputs.conf"
           regexp='\[splunktcp-ssl:\d+\]\n'
           replace=''
  when: splunk_inputs_conf.splunktcp_ssl.port is undefined
